### ISSUE TITLE
README image broken

### ISSUE THREAD

**Issue by KyleAMathews** [chriskjaer/react-lorem-image#2]
FYI

**Comment by chriskjaer** [comment]
Works on my machine™
![readme](https://cloud.githubusercontent.com/assets/2530413/9730620/fc13e56a-5617-11e5-8fec-02afd9fc7ffb.png)

**Comment by KyleAMathews** [comment]
Weird... checked it on my phone and it doesn't show up there as well.

**Comment by chriskjaer** [comment]
Hmm... It seems there might be something wrong with http://mustachify.me/ right now. But I'm still able to see the images just fine, so I'm not really sure what it is.

The images at http://placevaughnandfranco.it/ are working without any problems. I'll keep looking.
